[project]
name = "fundrive-lanzou"
version = "1.2.16"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "fundrive",]
[[project.authors]]
name = "farfun"
email = "farfarfun@qq.com"

[tool.uv.sources.fundrive]
workspace = true
