[project]
name = "fundrive-oss"
version = "1.2.14"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "fundrive", "oss2>=2.19.0",]
[[project.authors]]
name = "farfun"
email = "farfarfun@qq.com"

[tool.uv.sources.fundrive]
workspace = true
