[project]
name = "fundrive-alipan"
version = "1.2.18"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "aligo>=6.2.4", "fundrive",]
[[project.authors]]
name = "farfun"
email = "farfarfun@qq.com"

[tool.uv.sources.fundrive]
workspace = true
